trigger:
- master


pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Builders
  displayName: CodeQl CLI
  jobs:
  - job: Build
    displayName: Scan .Net and .Net core apps
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1

    - task: DotNetCoreCLI@2
      displayName: Restore web api
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)'

 
