trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CODEQL_BUNDLE_URL: https://github.com/github/codeql-action/releases/latest/download/codeql-bundle.tar.gz
  # CODEQL_EXTRACT_DIR: $(Pipeline.Workspace)/codeql

stages:
- stage: Builders
  displayName: CodeQl CLI
  jobs:
  - job: Build
    displayName: Scan .Net and .Net core apps
    steps:
    # - task: NuGetToolInstaller@1

    # - task: DotNetCoreCLI@2
    #   displayName: Restore web api
    #   inputs:
    #     command: 'restore'
    #     projects: '$(Build.SourcesDirectory)'

    # - task: Bash@3
    #   displayName: 'Download CodeQL CLI Bundle'
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       echo "Downloading CodeQL CLI from: $CODEQL_BUNDLE_URL"
    #       mkdir -p codeql
    #       curl -L $CODEQL_BUNDLE_URL -o codeql-bundle.tar.gz
    #       tar -xvzf codeql-bundle.tar.gz -C .
    #       ./codeql/codeql resolve languages
    #       echo "########################################Codeql database create######################################"
    #       ./codeql/codeql database create

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          #!/bin/bash
          
          set -e  # Exit on error
          
          # Step 1: Define variables
          CODEQL_BUNDLE_URL="https://github.com/github/codeql-action/releases/latest/download/codeql-bundle.tar.gz"
          CODEQL_DIR="$(pwd)/codeql"
          DATABASE_DIR="$(pwd)/codeql-database"
          SOURCE_DIR="$(pwd)"  # Change this if your code is elsewhere
          LANGUAGE="csharp"    # Change to your source language (e.g., cpp, java, csharp)
          
          # Step 2: Download CodeQL bundle
          echo "Downloading CodeQL CLI bundle..."
          mkdir -p "$CODEQL_DIR"
          curl -L "$CODEQL_BUNDLE_URL" -o codeql-bundle.tar.gz
          
          # Step 3: Extract the bundle
          echo "Extracting CodeQL CLI to $CODEQL_DIR..."
          tar -xzf codeql-bundle.tar.gz -C "$CODEQL_DIR"
          
          # Step 4: Add to PATH
          export PATH="$CODEQL_DIR/codeql:$PATH"
          
          # Step 5: Verify CLI with resolve languages
          echo "Available CodeQL languages:"
          codeql resolve languages
          
          # Step 6: Create CodeQL database
          echo "Creating CodeQL database at $DATABASE_DIR for language: $LANGUAGE..."
          codeql database create "$DATABASE_DIR" --language="$LANGUAGE" --source-root="$SOURCE_DIR"
          ls $DATABASE_DIR
          codeql database analyze "$DATABASE_DIR" --format=sarifv2.1.0 --output=codeql-csharp-results.sarif --threads=0 codeql/csharp-queries
          echo "✅ CodeQL Analyzed  successfully!"
          ls -a
          codeql github upload-results --repository="HarisEnmark/vulnerable_net_core" --ref="refs/heads/main" --commit="2ac5c1c85e8dc597670d323968aa8be2614992db" --sarif=codeql-csharp-results.sarif
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)