trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CODEQL_BUNDLE_URL: https://github.com/github/codeql-action/releases/latest/download/codeql-bundle.tar.gz
  # CODEQL_EXTRACT_DIR: $(Pipeline.Workspace)/codeql

stages:
- stage: Builders
  displayName: CodeQl CLI
  jobs:
  - job: Build
    displayName: Scan .Net and .Net core apps
    steps:
    # - task: NuGetToolInstaller@1

    # - task: DotNetCoreCLI@2
    #   displayName: Restore web api
    #   inputs:
    #     command: 'restore'
    #     projects: '$(Build.SourcesDirectory)'

    - task: Bash@3
      displayName: 'Download CodeQL CLI Bundle'
      inputs:
        targetType: 'inline'
        script: |
          echo "Downloading CodeQL CLI from: $CODEQL_BUNDLE_URL"
          mkdir -p codeql
          curl -L $CODEQL_BUNDLE_URL -o codeql-bundle.tar.gz
          tar -xvzf codeql-bundle.tar.gz -C .
          ./codeql resolve packs
          